ALTER TABLE services
	ALTER COLUMN svc_id SET NOT NULL,
	ALTER COLUMN vm_id SET NOT NULL,
	ALTER COLUMN team_id SET NOT NULL;

ALTER TABLE vms
	ALTER COLUMN vm_id SET NOT NULL,
	ALTER COLUMN team_id SET NOT NULL;
